line_length:
- 300

disabled_rules:
- force_cast
- identifier_name
- unused_optional_binding

opt_in_rules:
  - legacy_random
  - private_action
  - private_outlet
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
